[GLOBAL]
pants_version = "2.24.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.javascript",
  "pants.backend.experimental.javascript.lint.prettier",
]

[source]
root_patterns = ["apps/"]

[python]
interpreter_constraints = [">=3.8"]

[nodejs]
version = "v20"
package_managers = { "npm" = "10" }